import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: [
    "Click Hostel",
    "hospedagem São Paulo",
    "aluguel por temporada",
    "próximo ao Expo Imigrantes",
    "acomodação para eventos",
    "grupos e famílias",
    "hospedagem acessível",
    "paraolímpicos",
  ],
  openGraph: {
    title: "Click Hostel | Sua estadia sob medida em São Paulo",
    description:
      "Hospedagens versáteis e confortáveis em São Paulo — escolha entre quartos individuais, compartilhados ou casas completas. Ideal para expositores, turistas, atletas e grupos, com localização estratégica perto do Expo Imigrantes.",
    url: "https://www.clickhostel.com.br",
    siteName: "Click Hostel",
    locale: "pt_BR",
    type: "website",
  },
  metadataBase: new URL("https://www.clickhostel.com.br"),
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
